name: "ACSM Server"
description: "Downloads ePUB files from ACSM files"
version: "0.0.1"
slug: "acsm_server"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8095
